name: homelab
include:
  - authentik/compose.yaml
  - dockhand/compose.yaml
  - gitea/compose.yaml
  - homebridge/compose.yaml
  - homepage/compose.yaml
  - n8n/compose.yaml
  - ${NETWORKING_DIRECTORY:-fake-service}/compose.yaml
  - open-webui/compose.yaml
  - portainer/compose.yaml
  - traefik/compose.yaml
services:
  authentik-server:
    depends_on:
      traefik:
        condition: service_started
  dockhand:
    depends_on:
      traefik:
        condition: service_started
  gitea:
    depends_on:
      traefik:
        condition: service_started
  homebridge:
    depends_on:
      traefik:
        condition: service_started
  homepage:
    depends_on:
      traefik:
        condition: service_started
  n8n:
    depends_on:
      traefik:
        condition: service_started
  open-webui:
   depends_on:
      traefik:
        condition: service_started
  portainer:
    depends_on:
      traefik:
        condition: service_started
