services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    networks:
      - traefik-proxy
    ports:
     - ${PORT}:${PORT}/tcp
    environment:
      - TZ=${TZ}
      - ENABLE_AVAHI=1
    volumes:
      - ./data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8581 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.homebridge.rule=Host(`${SUBDOMAIN:-homebridge}.${DOMAIN_NAME:?DOMAIN_NAME not set}`)"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.routers.homebridge.tls.certresolver=cloudflare"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8581"
      - "traefik.http.services.homebridge.loadbalancer.server.scheme=http"

networks:
  traefik-proxy:
    external: true
