---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    label: Home
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: "{{HOMEPAGE_VAR_TZ}}"
    units: imperial
    cache: 5
    format:
      maximumFractionDigits: 0

- datetime:
    text_size: xl
    format:
      timeStyle: short
